server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    url: # 입력 해야 댑니당
    driver-class-name: # 입력 해야 댑니당
    hikari:
      username: # 입력 해야 댑니당
      password: # 입력 해야 댑니당
  jpa:
    show-sql: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger
  default-consumes-media-type: application/json
  default-produces-media-type: application/json