server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:mariadb://nas.leesunr.kr:53306/honey_mate_dev
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      username: ${username}
      password: ${password}
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger
  default-consumes-media-type: application/json
  default-produces-media-type: application/json