#name: deploy
#
#on:
#  push:
#    branches:
#      - master
#
#jobs:
#  build:
#    name: Deploy!
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Run scripts in server
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.EC2_HOST }}
#          port: ${{ secrets.EC2_PORT }}
#          username: ${{ secrets.EC2_USERNAME }}
#          key: ${{ secrets.EC2_PEM_KEY }}
#          script: |
#            cd /home/ec2-user/convenience-server
#            sh deploy.sh
